version: "3.8"
name: contacts_demo
services:
  app_contacts:  # Add Catalyst web service
    container_name: app_contacts
    networks:
      - contacts_network
    build: 
       context: .
       dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - CATALYST_DEBUG=1
      - DBIC_TRACE=1
      - SESSION_STORAGE_SECRET=${SESSION_STORAGE_SECRET}
      - CSRF_SECRET=${CSRF_SECRET}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=contact_dbuser
      - POSTGRES_DB=contacts
      - DB_HOST=db_contacts
      - DB_PORT=5432
      - SMTP_HOST=maildev
      - SMTP_PORT=1025
    volumes:
      - ".:/app"
    depends_on:
      db_contacts:
        condition: service_healthy
  db_contacts:  # Add PostgreSQL service
    container_name: db_contacts
    networks:
      - contacts_network
    build:
      context: .
      dockerfile: docker/Dockerfile-psql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contact_dbuser -d contacts"]
      interval: 1s
      timeout: 5s
      retries: 10
    user: postgres
    volumes:
      -  db_contacts_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=contact_dbuser
      - POSTGRES_DB=contacts
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  maildev:  # Add MailDev service
    container_name: maildev
    networks:
      - contacts_network
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  db_contacts_data:
    name: db_contacts_data
networks:
  contacts_network:
    name: contacts_network