FROM postgres:15.3

# OS Setup

# Make postgres user sudoer (maybe don't want this in production)
RUN apt-get update && apt-get install -y sudo
RUN echo "postgres        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
RUN sed -i "s/^.*requiretty/#Defaults requiretty/" /etc/sudoers

# pgcrypto
RUN apt-get update && apt-get install -y postgresql-contrib
# PostGIS
RUN apt-get update && apt-get install -y postgis postgresql-15-postgis-3
# pg_vector
RUN apt-get update && apt-get install -y postgresql-15-pgvector

# Add the database initialization script
ADD docker/psql/init.sql /docker-entrypoint-initdb.d


